# Generated by Django 3.0 on 2021-01-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='idProduct',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
