# Generated by Django 3.2.1 on 2021-06-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='idProduct',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
    ]
